version: '3.9'

services:
  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:16
    container_name: odoo-app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: >
      bash -c "while ! pg_isready -h db -U odoo; do sleep 1; done &&
               odoo -d odoo -i base --without-demo=all --db_user=odoo --db_password=odoo --db_host=db"
    volumes:
      - ./backend:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo

volumes:
  odoo-db-data:
  odoo-web-data:
